general:
  only-player: "&cКоманду может выполнять только игрок."
  unknown-subcommand: "&cНеизвестная подкоманда."
admin:
  only: "&cТолько администратор может использовать эту команду."
  usage: "&cИспользуйте /ta reload, /ta settings [город] или /ta <город> set <age|builds|bank> <значение>."
  set-usage: "&cИспользуйте /ta <город> set <age|builds|bank> <значение>."
  set:
    age: "&aВек города \"{town}\" установлен на {age}."
    age-invalid: "&cНекорректный номер века."
    build-invalid: "&cНеизвестная постройка."
    build: "&aЗдание {building} установлено на уровень {level} в городе \"{town}\"."
    bank-invalid: "&cНекорректное значение для казны."
    bank: "&aБаланс казны города \"{town}\" теперь {amount}."
  reload-success: "&aКонфигурации городов перезагружены."
town:
  usage: "&eИспользуйте /town new, delete, claim, unclaim, join, leave, invite, kick, bank, deposit, withdraw, settings, build, resources, info, age."
  create-usage: "&cИспользование: /town new <название>."
  empty-name: "&cНазвание города не может быть пустым."
  exists: "&cГород с таким названием уже существует."
  already-mayor: "&cВы уже являетесь мэром города."
  chunk-claimed: "&cТекущий чанк уже принадлежит другому городу."
  economy-missing: "&cЭкономика недоступна. Убедитесь, что установлен Vault и экономический плагин."
  missing-resources-header: "&eДля создания города:"
  requirements:
    cobblestone: "Булыжник {current}/{required}"
    wood: "Древесина {current}/{required}"
    iron: "Железо {current}/{required}"
    money: "Деньги {current}/{required}"
  created: "&aГород \"{name}\" успешно создан! Вы стали мэром."
  name-taken-during-confirm: "&cГород с таким названием уже был создан во время ожидания подтверждения."
  mayor-changed-during-confirm: "&cВы уже стали мэром другого города."
  chunk-claimed-during-confirm: "&cЭтот чанк уже занят, попробуйте снова в другом месте."
  withdraw-failed: "&cНе удалось снять средства: {error}"
  not-mayor-delete: "&cВы не мэр и не можете удалить город."
  deleted: "&eГород \"{name}\" удален. Все жители стали обычными игроками."
  not-mayor-claim: "&cТолько мэр может расширять территорию города."
  not-mayor-unclaim: "&cТолько мэр может освобождать чанки города."
  not-mayor-kick: "&cТолько мэр может исключать игроков из города."
  not-mayor-withdraw: "&cТолько мэр может снимать средства из казны."
  not-found: "&cГород с таким названием не найден."
  already-in-town: "&cВы уже состоите в городе."
  not-in-town: "&cВы не состоите ни в одном городе."
  mayor-cannot-leave: "&cМэр не может покинуть свой город."
  leave-failed: "&cНе удалось выйти из города, попробуйте снова."
  left: "&eВы покинули город \"{name}\"."
  join-usage: "&cИспользование: /town join <название>."
  join-failed: "&cНе удалось вступить в город, попробуйте снова."
  joined: "&aВы вступили в город \"{name}\"."
  closed: "&cГород закрыт для вступления. Попросите инвайт у мэра."
  claim:
    success: "&aЧанк успешно присоединен к городу. Стоимость: &e{cost}"
    already-owned: "&cЭтот чанк уже принадлежит вашему городу."
    other-owned: "&cЭтот чанк принадлежит городу \"{name}\"."
    not-enough-bank: "&cНедостаточно средств в казне. Требуется &e{cost}&c."
    failed: "&cНе удалось захватить чанк, попробуйте снова."
  unclaim:
    not-owned: "&cЭтот чанк никем не занят."
    other-town: "&cЭтот чанк принадлежит городу \"{name}\"."
    capital: "&cНельзя освободить столичный чанк."
    failed: "&cНе удалось освободить чанк, попробуйте снова."
    success: "&eЧанк освобожден и больше не принадлежит городу."
  invite-usage: "&cИспользование: /town invite <ник>."
  invite:
    offline: "&cИгрок не найден в сети."
    already-in-town: "&cИгрок уже состоит в городе."
    sent: "&aПриглашение отправлено игроку {player}."
  kick-usage: "&cИспользование: /town kick <ник>."
  kick:
    cannot-kick-mayor: "&cНельзя исключить мэра."
    not-member: "&cЭтот игрок не состоит в вашем городе."
    failed: "&cНе удалось исключить игрока."
    success: "&eИгрок {player} исключен из города."
    notify: "&cВы были исключены из города \"{name}\"."
  bank:
    balance: "&eВ казне города: &6{amount}"
  deposit-usage: "&cИспользование: /town deposit <сумма>."
  deposit:
    invalid-amount: "&cНекорректная сумма для пополнения."
    not-enough: "&cУ вас недостаточно средств для пополнения."
    failed: "&cНе удалось списать средства: {error}"
    success: "&aВ казну города \"{name}\" добавлено {amount}."
  withdraw-usage: "&cИспользование: /town withdraw <сумма>."
  withdraw:
    invalid-amount: "&cНекорректная сумма для снятия."
    not-enough: "&cНедостаточно средств в казне."
    failed: "&cНе удалось снять средства из казны, попробуйте снова."
    economy-failed: "&cНе удалось выдать средства: {error}"
    success: "&aВы сняли {amount} из казны города \"{name}\"."
  not-mayor-settings: "&cНастройки доступны только мэру города."
  not-mayor: "&cЭту операцию может выполнять только мэр города."
  not-member: "&cВы не состоите в городе."
  set:
    usage: "&cИспользование: /town set <center|color|name> ..."
    center-not-claimed: "&cЦентр можно ставить только в занятом чанке вашего города."
    center-failed: "&cНе удалось установить центр. Попробуйте снова."
    center-success: "&aНовый центр города установлен!"
    color-usage: "&cИспользование: /town set color <#RRGGBB> или <R G B>."
    color-invalid: "&cНекорректный цвет. Используйте #RRGGBB или три числа 0-255."
    color-success: "&aЦвет города обновлен на {color}."
    name-usage: "&cИспользование: /town set name <новое название>."
    name-taken: "&cГород с таким названием уже существует."
    name-success: "&aНазвание города изменено на \"{name}\"."
    name-broadcast: "Город \"{old}\" изменил название на \"{new}\"!"
    name-failed: "&cНе удалось переименовать город."
  resources:
    unavailable: "&cДобыча пока недоступна. Подождите до следующего сбора."
    inventory-full: "&cСначала освободи инвентарь города"
    claimed: "&aВы забрали {amount}x ресурсов из {type} (X {x}, Z {z}) в инвентарь города."
    title: "Городские ресурсы"
    type: "Ресурс:"
    coords: "Координаты:"
    reward: "Добыча:"
    discovered: "Обнаружен:"
    previous: "Предыдущая страница"
    next: "Следующая страница"
  rich-chunk-found: "&eЧанк X {x}, Z {z} оказался богат ресурсами! &bТип: {type}"
  rich-chunk-type: "&eВид чанка: &b{type}"
  inventory:
    missing: "&cСклад еще не построен."
  build:
    age: "&cНедостаточный век для строительства."
    dep: "&cТребуется постройка: {building}"
    money: "&cНедостаточно средств в казне. Нужно {cost}."
    success: "&aПостройка \"{building}\" обновлена до уровня {level}."
  info:
    title: "Информация о городе"
    no-town: "&cЗдесь нет занятого города."
    chunks: "Чанков: {count}"
    citizens: "Граждане: {count}"
    bank: "Казна: {amount}"
  age:
    chunks: "&cНужно минимум {required} занятых чанков."
    citizens: "&cНужно минимум {required} граждан."
    building: "&cТребуется построить: {building}"
    money: "&cНедостаточно средств. Нужно {cost}."
    success: "&aВы перешли в {age}! Награда: &e{reward}"
plot:
  usage: "&cИспользование: /plot <sell|buy|reclaim|settings|invite|kick|info>."
  not-in-town: "&cЭтот чанк не принадлежит городу."
  not-member: "&cВы не состоите в этом городе."
  not-owner: "&cВы не владелец этого плота."
  not-mayor: "&cЭту операцию может выполнять только мэр города."
  invalid-price: "&cУкажите корректную цену."
  sell-usage: "&cИспользование: /plot sell <сумма>."
  sell-success: "&aПлот выставлен на продажу за {price}."
  not-for-sale: "&cЭтот плот не продается."
  already-owner: "&cВы уже владелец этого плота."
  not-enough-money: "&cНедостаточно средств для покупки плота."
  buy-failed: "&cНе удалось купить плот: {error}"
  buy-success: "&aВы купили плот за {price}."
  sold-notify: "&aВаш плот купил {buyer} за {price}."
  reclaim-success: "&aПлот снова стал муниципальным."
  invite-usage: "&cИспользование: /plot invite <игрок>."
  invite:
    not-member: "&cЭтот игрок не состоит в городе."
  invite-success: "&aИгрок {player} добавлен в сожители."
  invite-notify: "&eВас добавили в сожители плота игрока {owner}."
  invite-already: "&cЭтот игрок уже в сожителях."
  kick-usage: "&cИспользование: /plot kick <игрок>."
  kick-success: "&aИгрок {player} удален из сожителей."
  kick-missing: "&cЭтот игрок не является сожителем."
  settings:
    title: "Настройки плота"
    label: "Флаги плота"
  info:
    title: "Информация о плоте"
    item-title: "Плот"
    owner: "Владелец: {owner}"
    owner-municipal: "Муниципальная земля"
    residents: "Сожители: {residents}"
    residents-none: "нет"
    sale: "Продается - {price}$"
    not-for-sale: "Непродается"
political-score:
  self: "&eВаши политические очки: &b{score}"
craft:
  require-town: "&cЧтобы скрафтить {item}, вступите в город и развивайте его."
  require-mayor: "&cКрафт {item} доступен только мэру города."
  require-age: "&cДля крафта {item} требуется век {age}."
  require-building: "&cДля крафта {item} требуется {building} {level} уровня."
confirmation:
  prompt: "&eВы действительно хотите {action}?"
  accepted: "&aДействие подтверждено: {action}"
  denied: "&cДействие отклонено: {action}"
  no-requests: "&cУ вас нет активных запросов."
  player-only-response: "&cТолько игрок может отвечать на запросы."
chunk:
  enter:
    town: "&6{town}{nation}"
    center: "&6{town}{nation} &b~Центр"
    wilderness: "&6~Дикая Земля"
settings:
  title:
    citizens: "&9Настройки города: {town}"
    outsiders: "&9Настройки города: {town}"
    defaults: "&9Настройки гостей (по умолчанию)"
  label:
    citizens: "Горожане"
    outsiders: "Гости"
    defaults: "Гости (по умолчанию)"
    open: "Город открыт"
  state:
    enabled: "&aРазрешено"
    disabled: "&cЗапрещено"
jobs:
  menu:
    title: "&8Работы"
  reward: "&a+{amount} монеты x{count}"
  selected: "&eВы выбрали работу: &6{job}"
  job:
    lumberjack: "Лесоруб"
    miner: "Шахтер"
    farmer: "Фермер"
    butcher: "Мясник"
    killer: "Киллер"
    unemployed: "Уволиться"
  lore:
    lumberjack:
      - "&8[&fОписание&8]:&7 Ваша задача рубить древесину любого вида."
      - "&8[&fЗарплата&8]:"
      - "&7- &f2.5 за дерево"
    miner:
      - "&8[&fОписание&8]:&7 Ваша задача добывать полезные ископаемые."
      - "&8[&fЗарплата&8]:"
      - "&7- &f0.2 за Камень"
      - "&7- &f2 за Уголь"
      - "&7- &f4 за Медную руду"
      - "&7- &f15 за Железную руду"
      - "&7- &f30 за Золотую руду"
      - "&7- &f10 за Лазурит/Редстоун"
      - "&7- &f40 за Алмазную руду"
      - "&7- &f80 за Изумрудную руду"
    farmer:
      - "&8[&fОписание&8]:&7 Ваша задача собирать спелый урожай."
      - "&8[&fЗарплата&8]:"
      - "&7- &f0.8 за Пшеницу"
      - "&7- &f0.8 за Картофель"
      - "&7- &f0.8 за Морковь"
      - "&7- &f0.8 за Свеклу"
    butcher:
      - "&8[&fОписание&8]:&7 Ваша задача убивать мирных животных."
      - "&8[&fЗарплата&8]:"
      - "&7- &f12 за любое мирное животное"
    killer:
      - "&8[&fОписание&8]:&7 Вы получаете цель на убийство игрока."
      - "&8[&fЗарплата&8]:"
      - "&7- &f150 за выполнение задания"
      - "&8[&fУсловия&8]:&7 15 минут на задачу, потом увольнение."
    unemployed:
      - "&8[&fОписание&8]:&7 Уволится с текущей работы."
  already-working: "&cВы уже работаете на данной работе!"
  unemployed-already: "&cВы нигде не работаете!"
  killer:
    task: "&eЗадание киллера: убить игрока &6{player}&e."
    completed: "&aЦель устранена. Следующее задание будет через час."
    failed: "&cВы не выполнили задание вовремя. Работа недоступна 24 часа."
    suspended: "&cВы временно отстранены от работы киллера."
    no-targets: "&cНет доступных целей для задания."