name: simpletown
version: '1.0'
main: com.simpletown.SimpleTownPlugin
api-version: '1.20'
load: STARTUP
authors: [ holynwk ]
softdepend:
  - BlueMap
depend:
  - Vault
description: Управление городами и странами с интеграцией BlueMap и Vault.
commands:
  town:
    aliases: [t]
    description: Управление городами SimpleTown
  townadmin:
      aliases: [ta]
      description: Администрирование SimpleTown